/crazyflie_server:
  ros__parameters:
    # simulation related
    sim:
      max_dt: 0 #0.1              # artificially limit the step() function (set to 0 to disable)
      backend: none                 # see backend folder for a list 
      visualizations:             # see visualization folder for a list
        rviz:
          enabled: false
        pdf:
          enabled: false
          output_file: "result.pdf"
        blender:
          enabled: true
          auto_yaw:     # constant yaw rotation applied to cf_cameras only
            enabled: true
            radps: 5   # radians per second
          fps: 1           # frames per second
          cf_cameras:      # names of crazyflies with cameras on them if enabled in `crazyflies.yaml`
            cf231:
              calibration:
                camera_matrix: [170.0, 0.0, 160.0, 0.0, 170.0, 160.0, 0.0, 0.0, 1.0] # matrix in row-major order
                dist_coeff: [0,0,0,0,0]
                tvec: [0,0,0]
                rvec: [1.2092,-1.2092,1.2092]   # 0 deg tilt
            cf5:
              calibration:
                camera_matrix: [170.0, 0.0, 160.0, 0.0, 170.0, 160.0, 0.0, 0.0, 1.0] # matrix in row-major order
                dist_coeff: [0,0,0,0,0]
                tvec: [0,0,0]
                rvec: [ 0.61394313, -0.61394313,  1.48218982]   # 45 deg tilt
            cf6:
              calibration:
                camera_matrix: [170.0, 0.0, 160.0, 0.0, 170.0, 160.0, 0.0, 0.0, 1.0] # matrix in row-major order
                dist_coeff: [0,0,0,0,0]
                tvec: [0,0,0]
                rvec: [0.0,0.0,1.5707963267948966]    # 90 deg tilt
            cf7:
              calibration:
                camera_matrix: [170.0, 0.0, 160.0, 0.0, 170.0, 160.0, 0.0, 0.0, 1.0] # matrix in row-major order
                dist_coeff: [0,0,0,0,0]
                tvec: [0,0,0]
                rvec: [ 0.61394313, -0.61394313,  1.48218982]   # 45 deg tilt
            cf8:
              calibration:
                camera_matrix: [170.0, 0.0, 160.0, 0.0, 170.0, 160.0, 0.0, 0.0, 1.0] # matrix in row-major order
                dist_coeff: [0,0,0,0,0]
                tvec: [0,0,0]
                rvec: [1.2092,-1.2092,1.2092]   # 0 deg tilt
          observer:        # static observer camera 
            enabled: false
            pos: [-0.1,0,1]
            quat: [1,0,0,0]
            calibration:
              camera_matrix: [170.0, 0.0, 160.0, 0.0, 170.0, 160.0, 0.0, 0.0, 1.0] # matrix in row-major order
              dist_coeff: [0,0,0,0,0]
              tvec: [0,0,0]
              #rvec: [1.2092,-1.2092,1.2092]
              rvec: [ 0.61394313, -0.61394313, 1.48218982]
      controller: mellinger # none, pid, mellinger
